logging:
  level:
    org:
      springframework:
        security: INFO
spring:
  # thymeleaf 配置
  thymeleaf: 
    cache: false
  # mysql 配置
ms:
 db:
   url: jdbc:mysql://127.0.0.1:3306/security_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
   username: root
   password: root
   driverClassName: com.mysql.jdbc.Driver
server:
  port: 7777
