server:
  port: 8888
auth:
  url: http://127.0.0.1:7777/auth/oauthLogin?notifyUrl=%s&appId=%s&appSecret=%s&additionalParam=%s
  #appId: OaH1heR2E4eGnBr87Br8F
  #appSecret: gY/Hauph1tqvVWiH4atxteSH8sRX03IDXRIQi03DVTFGzKfz8ZtGi
  appId: gY/Hauph1tqvVWiH4atxte
  appSecret: OaH1heR2E4eGnBr87Br8FgY/Hauph1tqvVWiH4atxtegY/Hauph
  notifyUrl: http://127.0.0.1:8888/success/callback
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接